
stages:
  - prepare
  - lint
  - test
  - build

image: node:10

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - ./node_modules/

install:
  stage: prepare
  tags:
    - docker
  script:
    - npm install --unsafe-perm

lint-critical:
  stage: lint
  tags:
    - docker
  script:
    - npm run lint:critical

lint:
  stage: lint
  tags:
    - docker
  script:
    - npm run lint
  allow_failure: true

test:
  stage: test
  tags:
    - docker
  services:
    - name: kennethreitz/httpbin
      alias: httpbin
  script:
    - export FETCH_HELPER_TEST_ENDPOINT='http://httpbin'
    - npm run test

build:
  stage: build
  tags:
    - docker
  script:
    - npm run build
    - npm pack
